const patentes = [
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Ontoolsearch",
    "Nº referencia de la solicitud:": "VA-146-2011",
    "Tipo:": "Registro de Propiedad intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Guillermo Vega Gorgojo.",
    "Fecha solicitud:": NaN,
    "Breve Descripción/Resumen:": "Con este sistema pueden realizarse dos tipos de actividades: la búsqueda de herramientas y el análisis de los resultados. Inicialmente, los profesores pueden formular preguntas de tipos de herramientas tales como pizarras (whiteboards) o editores de cuestionarios (questionnaire editors); también es posible preguntar por tareas que pueden apoyarse con una herramienta como por ejemplo edición de documentos (document edition) o comunicación basada en mensajes de texto (communication based on text messages). Las herramientas obtenidas se presentan por pantalla, permitiendo a los profesores analizar cuáles son más apropiadas para sus necesidades.",
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": NaN
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": " - ",
    "Nº referencia de la solicitud:": "VA-87-2021",
    "Tipo:": "Registro de Propiedad intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Óscar García Espinilla, Pablo Arlanzón López, Mª Isabel López Gálvez, Juan Carlos Pastor Jimeno.",
    "Fecha solicitud:": NaN,
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": NaN
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": " - ",
    "Nº referencia de la solicitud:": "VA-88-2021",
    "Tipo:": "Registro de Propiedad intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Óscar García Espinilla, Pablo Arlanzón López, Mª Isabel López Gálvez, Juan Carlos Pastor Jimeno.",
    "Fecha solicitud:": NaN,
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": NaN
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": " - ",
    "Nº referencia de la solicitud:": "VA-89-2021",
    "Tipo:": "Registro de Propiedad intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Óscar García Espinilla, Pablo Arlanzón López, Mª Isabel López Gálvez, Juan Carlos Pastor Jimeno.",
    "Fecha solicitud:": NaN,
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": NaN
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Grupos de cepas hipovirulentas denominados E-2 y E-3 del hongo Criphoneptria parasítica para el control biológico del Chancro del Cataño.",
    "Nº referencia de la solicitud:": "P9702274",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Manuel Berrocal del Brio.",
    "Fecha solicitud:": "00/01/1900",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": NaN
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Genes de las proteínas inactivadoras de ribosomas de bulbos y hojas de Muscari armeniacum denominadas musarminas, procedimiento para su obtencióny aplicaciones de utilidad en la terapia del cáncer y del sida y en la producción de plantas fitopatogénicos y en virus vegetales",
    "Nº referencia de la solicitud:": " - ",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Tomás Girbés Juan.",
    "Fecha solicitud:": "00/01/1900",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": NaN
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "CaptuRING: An Open Source Software for Sequential Digitization",
    "Nº referencia de la solicitud:": "765- 645039",
    "Tipo:": "Registro de Propiedad Intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Miguel Garcia Hidalgo, Ángel García Pedrero, Daniel Colón Sánchez, Gabriel Sangüesa Barreda, Vicente Fernando Rozas Ortiz, Jose Miguel Olano Mendoza, Víctor Alonso Gómez.",
    "Fecha solicitud:": "16/04/2475",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": "digitalizacion secuencial",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": NaN
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "SISTEMA DE TRATAMIENTO DE AGUAS",
    "Nº referencia de la solicitud:": "P202231124",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Ruiz Palomar César, Gonzalo Ibrahim Félix.",
    "Fecha solicitud:": "30/12/2022",
    "Breve Descripción/Resumen:": "SISTEMA DE TRATAMIENTO DE AGUAS",
    "Palabras Clave:": "tratamiento aguas",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "SISTEMA INALÁMBRICO PARA LA INSPECCIÓN DE MÓDULOS FOTOVOLTAICOS EN PLANTA MEDIANTE ELECTROLUMINISCENCIA",
    "Nº referencia de la solicitud:": "P202231117",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Padilla Marcos Miguel Ángel, Conde Pérez Mariano.",
    "Fecha solicitud:": "29/12/2022",
    "Breve Descripción/Resumen:": "SISTEMA INALÁMBRICO PARA LA INSPECCIÓN DE MÓDULOS FOTOVOLTAICOS EN PLANTA MEDIANTE ELECTROLUMINISCENCIA",
    "Palabras Clave:": "inspeccion, módulos dotovoltaicos, electroluministcencia",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "SISTEMA DE PROTECCIÓN CONTRA EL CONTAGIO DE VIRUS EN PUESTOS DE TRABAJO DE OFICINA",
    "Nº referencia de la solicitud:": "U202232141",
    "Tipo:": "Modelo de utilidad",
    "Apellidos y Nombre/ Persona Jurídica:": "Diaz Vega Rafael, VALBUENA GARCÍA Francisco José, GRIJALBA BENGOECHEA Alberto, VILLAGRÁ HERRERO Rafael, López Antuñano Marta, RAMOS MANZANO Francisco Julian.",
    "Fecha solicitud:": "21/12/2022",
    "Breve Descripción/Resumen:": "SISTEMA DE PROTECCIÓN CONTRA EL CONTAGIO DE VIRUS EN PUESTOS DE TRABAJO DE OFICINA",
    "Palabras Clave:": "contagio, virus, puestos trabajo, seguridad laboral",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "SISTEMA Y MÉTODO PARA ANÁLISIS DE MATERIA PRIMA",
    "Nº referencia de la solicitud:": "P202231006",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "ARÉVALO GALÁN Vanesa, Casado Sanz Milagros.",
    "Fecha solicitud:": "22/11/2022",
    "Breve Descripción/Resumen:": "SISTEMA Y MÉTODO PARA ANÁLISIS DE MATERIA PRIMA",
    "Palabras Clave:": "análisis, materia prima",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Juego de construcción para niños",
    "Nº referencia de la solicitud:": "P202231004",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Delgado Martín Alejandra, Moral garcía Alvaro, Gómez Méndez Ruben.",
    "Fecha solicitud:": "22/11/2022",
    "Breve Descripción/Resumen:": "Juego de construcción para niños",
    "Palabras Clave:": "juego construcción, niños",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "PROCEDIMIENTO DE OBTENCIÓN DE MEMBRANAS DE GRAFENO NANOPOROSAS, MEMBRANAS OBTENIDAS Y SU USO",
    "Nº referencia de la solicitud:": "P202231002",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "de la Fuente Ballesteros Adrián.",
    "Fecha solicitud:": "21/11/2022",
    "Breve Descripción/Resumen:": "PROCEDIMIENTO DE OBTENCIÓN DE MEMBRANAS DE GRAFENO NANOPOROSAS, MEMBRANAS OBTENIDAS Y SU USO",
    "Palabras Clave:": "obtención grafeno, membranas",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Dispositivo de respuesta en escuelas",
    "Nº referencia de la solicitud:": "P202230985",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Fuentes Moncayola Elisa, Charouni Moutaa Mohamed.",
    "Fecha solicitud:": "15/11/2022",
    "Breve Descripción/Resumen:": "Dispositivo de respuesta en escuelas",
    "Palabras Clave:": "respuestas, escuelas",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "ALIMENTO ANÁLOGO DE LA CARNE QUE COMPRENDE MICOPROTEÍNAS Y MICROALGAS",
    "Nº referencia de la solicitud:": "P202230984",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "de la Fuente Ballesteros Adrián, Vela Corona Antonio José.",
    "Fecha solicitud:": "15/11/2022",
    "Breve Descripción/Resumen:": "ALIMENTO ANÁLOGO DE LA CARNE QUE COMPRENDE MICOPROTEÍNAS Y MICROALGAS",
    "Palabras Clave:": "carne, algas, microproteinas",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "DISPOSITIVO PORTÁTIL DE LECTURA EN BRAILLE PARA PERSONAS CON DISCAPACIDAD VISUAL",
    "Nº referencia de la solicitud:": "U202231834",
    "Tipo:": "Modelo de utilidad",
    "Apellidos y Nombre/ Persona Jurídica:": "Perez Callejo Sergio, Merayo Álvarez Noemí.",
    "Fecha solicitud:": "08/11/2022",
    "Breve Descripción/Resumen:": "DISPOSITIVO PORTÁTIL DE LECTURA EN BRAILLE PARA PERSONAS CON DISCAPACIDAD VISUAL",
    "Palabras Clave:": "Lectura, braile, discapacidad visual",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Software de control del Sistema de Bloqueo Solar Inteligente",
    "Nº referencia de la solicitud:": "765-995064",
    "Tipo:": "Registro de Propiedad Intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Mario Perez Rodriguez.",
    "Fecha solicitud:": "07/11/2022",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": "bloque solar",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "MÉTODO PARA LA OBTENCIÓN DE POLICAPROLACTONA (PCL) A PARTIR DE POLICAPROLACTAMA (NYLON-6)",
    "Nº referencia de la solicitud:": "P202230932",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Tomillo Barrio GONZALO, Gutierrez Fradejas Raúl.",
    "Fecha solicitud:": "28/10/2022",
    "Breve Descripción/Resumen:": "MÉTODO PARA LA OBTENCIÓN DE POLICAPROLACTONA (PCL) A PARTIR DE POLICAPROLACTAMA (NYLON-6)",
    "Palabras Clave:": "OBTENCIÓN DE POLICAPROLACTONA, PCL, NYLON-6",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Dispositivo de iluminación",
    "Nº referencia de la solicitud:": "P202230917",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "López Pérez Lucía.",
    "Fecha solicitud:": "25/10/2022",
    "Breve Descripción/Resumen:": "Dispositivo de iluminación",
    "Palabras Clave:": "iluminacion, lampara",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Control de movilidad de un robot en cirugías laparoscópicas por reorientación mediante el contacto",
    "Nº referencia de la solicitud:": "765-977701",
    "Tipo:": "Registro de Propiedad Intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Carlos Fonturbel Mediavilla.",
    "Fecha solicitud:": "24/10/2022",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": "laparoscopia",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "SISTEMA DE BLOQUEO SOLAR INTELIGENTE",
    "Nº referencia de la solicitud:": "P202230898",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Pérez Rodríguez Mario.",
    "Fecha solicitud:": "19/10/2022",
    "Breve Descripción/Resumen:": "SISTEMA DE BLOQUEO SOLAR INTELIGENTE",
    "Palabras Clave:": "bloqueo solar, sistema inteligente",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Trampa para la captura de artrópodos",
    "Nº referencia de la solicitud:": "P202230882",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Fernandez Martinez Diego.",
    "Fecha solicitud:": "13/10/2022",
    "Breve Descripción/Resumen:": "Trampa para la captura de artrópodos",
    "Palabras Clave:": "trampa, insectos, artrópodos",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Sistema de producción de biogás",
    "Nº referencia de la solicitud:": "P202230870",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Carcía Álvaro Alfonso, de Godos Crespo Ignacio, Muñoz Torre Raúl, Hermosilla Redondo Daphne.",
    "Fecha solicitud:": "10/10/2022",
    "Breve Descripción/Resumen:": "Sistema de producción de biogás",
    "Palabras Clave:": "biogás",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Guia de recursos para la prevención y abordaje del bulling en la formación inicial del profesorado de la Universidad de Valladolid",
    "Nº referencia de la solicitud:": "765-958049",
    "Tipo:": "Registro de Propiedad Intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Patricia Gonzalez Arratia.",
    "Fecha solicitud:": "06/10/2022",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": "bulling",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "SISTEMA DE DESINFECCIÓN Y DESCONTAMINACIÓN DE AGUAS\nRESIDUALES Y ACUÍFEROS CONTAMINADOS",
    "Nº referencia de la solicitud:": "P202230816",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Carlos Sanz Miguel.",
    "Fecha solicitud:": "22/09/2022",
    "Breve Descripción/Resumen:": "SISTEMA DE DESINFECCIÓN Y DESCONTAMINACIÓN DE AGUAS\nRESIDUALES Y ACUÍFEROS CONTAMINADOS",
    "Palabras Clave:": "Desinfeccióm, aguas residuales, acuíferos",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "DISPOSITIVO DE MONITORIZACIÓN DE CONTAMINACIÓN Y SISTEMA QUE LO COMPRENDE",
    "Nº referencia de la solicitud:": "U202231491",
    "Tipo:": "Modelo de utilidad",
    "Apellidos y Nombre/ Persona Jurídica:": "Casado Rodríguez Míriam.",
    "Fecha solicitud:": "14/09/2022",
    "Breve Descripción/Resumen:": "DISPOSITIVO DE MONITORIZACIÓN DE CONTAMINACIÓN Y SISTEMA QUE LO COMPRENDE",
    "Palabras Clave:": "monitorización, contaminazión",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "e-poliTrauma: Aplicación móvil para la evaluación inicial del\npaciente politraumatizado",
    "Nº referencia de la solicitud:": "765-887553",
    "Tipo:": "Registro de Propiedad Intelectual",
    "Apellidos y Nombre/ Persona Jurídica:": "Isabel De la Torre Díaz, Miguel Cantón González, Francisco Martín Rodriguez.",
    "Fecha solicitud:": "03/08/2022",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": "politraumatismos",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "NANOMATERIAL BASADO EN EL AUTOENSAMBLAJE DE g-C3N4 Y OLIGÓMEROS DE QUITOSANO, PROCESO DE OBTENCIÓN Y USOS",
    "Nº referencia de la solicitud:": "P202230688",
    "Tipo:": "Patente",
    "Apellidos y Nombre/ Persona Jurídica:": "Eva Sanchez Hernandez, Alberto Santiago Aliste, Jesús Martin Gil, Pablo Martín Ramos.",
    "Fecha solicitud:": "20/07/2022",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "Sistema de climatización y container que lo comprende",
    "Nº referencia de la solicitud:": "U202231210",
    "Tipo:": "Modelo de utilidad",
    "Apellidos y Nombre/ Persona Jurídica:": "Mario Gómez Carnero, Vicente Garrido Freijanes, Miguel Villagrá García.",
    "Fecha solicitud:": "20/07/2022",
    "Breve Descripción/Resumen:": "Sistema de climatización y container que lo comprende",
    "Palabras Clave:": "climatizacion",
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  },
  {
    "Universidad de Origen:": "Valladolid",
    "Título:": "LLAVE AJUSTABLE",
    "Nº referencia de la solicitud:": "U202231174",
    "Tipo:": "Modelo de utilidad",
    "Apellidos y Nombre/ Persona Jurídica:": "Celia Andrés Juan, EDUARDO PÉREZ LEBEÑA.",
    "Fecha solicitud:": "12/07/2022",
    "Breve Descripción/Resumen:": NaN,
    "Palabras Clave:": NaN,
    "Clasificación: (Códigos UNESCO)": NaN,
    "Posible aplicación industrial": NaN,
    "Año solicitud": 2022.0
  }
];
